// Stable, machine-readable error codes — the single source of truth for the
// `code` field of the error envelope. Add codes here as sites are migrated; no
// speculative codes (YAGNI).
const errorCodes = Object.freeze({
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',

  // Idempotency (already used by the idempotency middleware)
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_REQUEST_IN_PROGRESS: 'IDEMPOTENCY_REQUEST_IN_PROGRESS',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // Trading (Task 7)
  TRADING_PAIR_NOT_FOUND: 'TRADING_PAIR_NOT_FOUND',
  INVALID_ORDER: 'INVALID_ORDER',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

  // Transferencia (Task 1)
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  VERIFICATION_CODE_INVALID: 'VERIFICATION_CODE_INVALID',
  VERIFICATION_CODE_EXPIRED: 'VERIFICATION_CODE_EXPIRED',
  TRANSFER_FORBIDDEN: 'TRANSFER_FORBIDDEN',
  TRANSFER_INVALID_STATE: 'TRANSFER_INVALID_STATE',
  TRANSFER_INVALID_INPUT: 'TRANSFER_INVALID_INPUT',
  TRANSFER_RESOURCE_NOT_FOUND: 'TRANSFER_RESOURCE_NOT_FOUND',

  // TransaccionBlockchain (this file)
  WITHDRAWAL_VALIDATION_FAILED: 'WITHDRAWAL_VALIDATION_FAILED',
  WITHDRAWAL_INVALID_ADDRESS: 'WITHDRAWAL_INVALID_ADDRESS',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_FORBIDDEN: 'TRANSACTION_FORBIDDEN',
  TRANSACTION_INVALID_STATE: 'TRANSACTION_INVALID_STATE',
  DEPOSIT_CRYPTO_NOT_FOUND: 'DEPOSIT_CRYPTO_NOT_FOUND',
  DEPOSIT_ADDRESS_GENERATION_FAILED: 'DEPOSIT_ADDRESS_GENERATION_FAILED',
  ADMIN_FORBIDDEN: 'ADMIN_FORBIDDEN',

  // IntercambioExchange (crypto↔crypto swap)
  EXCHANGE_INVALID_INPUT: 'EXCHANGE_INVALID_INPUT',
  EXCHANGE_PAIR_NOT_FOUND: 'EXCHANGE_PAIR_NOT_FOUND',
  EXCHANGE_PAIR_NO_PRICE: 'EXCHANGE_PAIR_NO_PRICE',
  EXCHANGE_USER_NOT_FOUND: 'EXCHANGE_USER_NOT_FOUND',
  EXCHANGE_DAILY_LIMIT_EXCEEDED: 'EXCHANGE_DAILY_LIMIT_EXCEEDED',
  EXCHANGE_INSUFFICIENT_BALANCE: 'EXCHANGE_INSUFFICIENT_BALANCE',
  EXCHANGE_NOT_FOUND: 'EXCHANGE_NOT_FOUND',
  EXCHANGE_INVALID_STATUS: 'EXCHANGE_INVALID_STATUS',

  // OfertaP2P
  OFFER_DIRECCION_FIAT_REQUIRED: 'OFFER_DIRECCION_FIAT_REQUIRED',
  OFFER_PAYMENT_METHODS_REQUIRED: 'OFFER_PAYMENT_METHODS_REQUIRED',
  OFFER_NOT_FOUND: 'OFFER_NOT_FOUND',
  OFFER_FORBIDDEN: 'OFFER_FORBIDDEN',
  OFFER_INVALID_TYPE: 'OFFER_INVALID_TYPE',
  OFFER_SEARCH_TERM_REQUIRED: 'OFFER_SEARCH_TERM_REQUIRED',
  OFFER_COMPATIBLE_PARAMS_REQUIRED: 'OFFER_COMPATIBLE_PARAMS_REQUIRED',
  OFFER_CANTIDAD_REQUIRED: 'OFFER_CANTIDAD_REQUIRED',

  // TransaccionesP2P
  P2P_TX_NOT_FOUND: 'P2P_TX_NOT_FOUND',
  P2P_TX_FORBIDDEN: 'P2P_TX_FORBIDDEN',
  P2P_TX_OFFER_NOT_FOUND: 'P2P_TX_OFFER_NOT_FOUND',
  P2P_TX_OWN_OFFER: 'P2P_TX_OWN_OFFER',
  P2P_TX_ADMIN_REQUIRED: 'P2P_TX_ADMIN_REQUIRED',
  P2P_TX_INVALID_STATE: 'P2P_TX_INVALID_STATE',
});

module.exports = errorCodes;
